In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("data.csv") # gerei nomes aleatórios de pessoas para um conjunto de dados ficticio

In [ ]:
df

             nome_aluno
0        Gerrie Pernell
1        Marielle Celli
2       Malvina Volante
3         Michal Spoure
4      Clotilda Donaghy
...                 ...
9995         Tedi Dyble
9996        Nedi Gasker
9997    Dickie Kennelly
9998      Devland Tames
9999  Valencia Stilwell

[10000 rows x 1 columns]

In [ ]:
len(df["nome_aluno"].unique())

10000

In [ ]:
import numpy as np

In [ ]:
random_ages = np.random.randint(low=16, high=65, size=10_000)

In [ ]:
df["idade_aluno"] = random_ages

In [ ]:
df

             nome_aluno  idade_aluno
0        Gerrie Pernell           35
1        Marielle Celli           57
2       Malvina Volante           56
3         Michal Spoure           38
4      Clotilda Donaghy           17
...                 ...          ...
9995         Tedi Dyble           24
9996        Nedi Gasker           52
9997    Dickie Kennelly           17
9998      Devland Tames           54
9999  Valencia Stilwell           62

[10000 rows x 2 columns]

In [ ]:
df['data_inicio'] = pd.to_datetime(
    np.random.choice(pd.date_range('2024-01-01', '2025-12-01'), size=len(df))
)

In [ ]:
df

             nome_aluno  idade_aluno data_inicio
0        Gerrie Pernell           35  2024-07-10
1        Marielle Celli           57  2025-04-14
2       Malvina Volante           56  2024-11-20
3         Michal Spoure           38  2025-09-12
4      Clotilda Donaghy           17  2024-05-02
...                 ...          ...         ...
9995         Tedi Dyble           24  2024-04-18
9996        Nedi Gasker           52  2025-06-08
9997    Dickie Kennelly           17  2024-04-16
9998      Devland Tames           54  2024-05-15
9999  Valencia Stilwell           62  2025-09-01

[10000 rows x 3 columns]

In [ ]:
checkins = []

for i, row in df.iterrows():
    nome = row['nome_aluno']
    data_inicio = row['data_inicio']

    n_checkins = np.random.randint(20, 150) # cada aluno terá entre 20 e 150 checkins

    datas_checkin = pd.date_range(start=data_inicio, end='2025-04-03').to_pydatetime()

    if len(datas_checkin) == 0:
        continue

    datas_aleatorias = np.random.choice(datas_checkin, size=n_checkins, replace=True)

    for data in datas_aleatorias:
        checkins.append({
            'nome_aluno': nome,
            'data_checkin': pd.to_datetime(data)
        })

df_checkins = pd.DataFrame(checkins)
df_checkins.sort_values(by=['nome_aluno', 'data_checkin'], inplace=True)
df_checkins.reset_index(drop=True, inplace=True)

df_checkins['id_checkin'] = range(1, len(df_checkins)+1) # adiciona id de checkin

In [ ]:
df_checkins.sample(5)

               nome_aluno data_checkin  id_checkin
219669     Glenda Skeeles   2025-02-20      219670
101969  Christyna Woodfin   2025-03-22      101970
166231     Ellis Hucknall   2024-07-14      166232
283346    Julia Floodgate   2024-12-04      283347
158244       Ebba Drillot   2025-01-03      158245

In [ ]:
!pip install pytz

Requirement already satisfied: pytz in /usr/local/lib/python3.11/dist-packages (2025.2)

In [ ]:
import datetime
import random

tz = "America/Sao_Paulo"

def gerar_data_horario_aleatorio(data):
    hora = random.randint(6, 22)
    minuto = random.randint(0, 59)
    segundo = random.randint(0, 59)

    dt = pd.Timestamp(data).replace(hour=hora, minute=minuto, second=segundo)
    return dt.tz_localize(tz)

def gerar_data_checkout(data_checkin):
    minutos_extra = random.randint(40, 60)
    return data_checkin + pd.Timedelta(minutes=minutos_extra)

df_checkins['data_checkin'] = df_checkins['data_checkin'].apply(gerar_data_horario_aleatorio)
df_checkins['data_checkout'] = df_checkins['data_checkin'].apply(gerar_data_checkout)

In [ ]:
df_checkins

,nome_aluno,data_checkin,id_checkin,data_checkout
0,Aarika Vigneron,2025-04-01 16:36:01-03:00,1,2025-04-01 17:32:01-03:00
1,Aarika Vigneron,2025-04-01 17:50:24-03:00,2,2025-04-01 18:48:24-03:00
2,Aarika Vigneron,2025-04-01 20:12:08-03:00,3,2025-04-01 21:10:08-03:00
3,Aarika Vigneron,2025-04-01 08:06:53-03:00,4,2025-04-01 09:02:53-03:00
4,Aarika Vigneron,2025-04-01 14:12:57-03:00,5,2025-04-01 14:55:57-03:00
...,...,...,...,...
557995,Zuzana Whifen,2025-03-24 08:07:20-03:00,557996,2025-03-24 08:50:20-03:00
557996,Zuzana Whifen,2025-03-25 21:42:12-03:00,557997,2025-03-25 22:34:12-03:00
557997,Zuzana Whifen,2025-03-26 17:06:23-03:00,557998,2025-03-26 17:49:23-03:00
557998,Zuzana Whifen,2025-04-01 12:49:50-03:00,557999,2025-04-01 13:42:50-03:00
557999,Zuzana Whifen,2025-04-03 21:13:48-03:00,558000,2025-04-03 22:02:48-03:00

In [ ]:
df["data_inicio"].sample(5)

1082   2025-10-13
942    2025-05-02
2526   2024-11-26
2343   2024-05-25
474    2025-02-08
Name: data_inicio, dtype: datetime64[ns]

In [ ]:
df['data_inicio'] = pd.to_datetime(df['data_inicio'])

def gerar_data_fim(data_inicio):
    if random.random() < 0.3:
        dias_extra = random.randint(30, 730)
        return data_inicio + pd.Timedelta(days=dias_extra)
    return pd.NaT  # Se não cancelar, retorna NaT (indica que o aluno ainda está ativo)

df['data_fim'] = df['data_inicio'].apply(gerar_data_fim)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nome_aluno   10000 non-null  object
 1   idade_aluno  10000 non-null  int64
 2   data_inicio  10000 non-null  datetime64[ns]
 3   data_fim     2977 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(1)
memory usage: 312.6+ KB

In [ ]:
df_checkins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558000 entries, 0 to 557999
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   nome_aluno     558000 non-null  object
 1   data_checkin   558000 non-null  datetime64[ns, America/Sao_Paulo]
 2   id_checkin     558000 non-null  int64
 3   data_checkout  558000 non-null  datetime64[ns, America/Sao_Paulo]
dtypes: datetime64[ns, America/Sao_Paulo](2), int64(1), object(1)
memory usage: 17.0+ MB

In [ ]:
df["data_inicio"] = pd.to_datetime(df['data_inicio'], format="%Y-%m-%d")

In [ ]:
df["data_fim"] = pd.to_datetime(df['data_fim'], format="%Y-%m-%d")

In [ ]:
df_checkins["data_checkout"] = pd.to_datetime(df_checkins['data_checkout'], format="%Y-%m-%d %H:%M:%S%z")
df_checkins["data_checkin"] = pd.to_datetime(df_checkins['data_checkin'], format="%Y-%m-%d %H:%M:%S%z")

In [ ]:
# Garantir que TODAS as datas sejam UTC e REMOVER o fuso horário
df_checkins["data_checkin"] = df_checkins["data_checkin"].dt.tz_convert("UTC").dt.tz_localize(None)
df_checkins["data_checkout"] = df_checkins["data_checkout"].dt.tz_convert("UTC").dt.tz_localize(None)

df["data_inicio"] = df["data_inicio"].dt.tz_localize("UTC")
df["data_fim"] = df["data_fim"].dt.tz_localize("UTC", ambiguous="NaT")  # Evita erro em NaN

In [ ]:
df_checkins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558000 entries, 0 to 557999
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   nome_aluno     558000 non-null  object
 1   data_checkin   558000 non-null  datetime64[ns]
 2   id_checkin     558000 non-null  int64
 3   data_checkout  558000 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(1)
memory usage: 17.0+ MB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nome_aluno   10000 non-null  object
 1   idade_aluno  10000 non-null  int64
 2   data_inicio  10000 non-null  datetime64[ns, UTC]
 3   data_fim     2977 non-null   datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](2), int64(1), object(1)
memory usage: 312.6+ KB

In [ ]:
# Fazer merge mantendo múltiplos check-ins por aluno
df_merged = df_checkins.merge(df, on="nome_aluno", how="left")

In [ ]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 535299 entries, 0 to 557999
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   nome_aluno     535299 non-null  object
 1   data_checkin   535299 non-null  datetime64[ns]
 2   id_checkin     535299 non-null  int64
 3   data_checkout  535299 non-null  datetime64[ns]
 4   idade_aluno    535299 non-null  int64
 5   data_inicio    535299 non-null  datetime64[ns]
 6   data_fim       143435 non-null  datetime64[ns]
dtypes: datetime64[ns](4), int64(2), object(1)
memory usage: 32.7+ MB

In [ ]:
df_merged["data_inicio"] = df_merged["data_inicio"].dt.tz_localize(None)
df_merged["data_fim"] = df_merged["data_fim"].dt.tz_localize(None)

In [ ]:
df_merged = df_merged[
    (df_merged["data_checkin"] >= df_merged["data_inicio"]) &
    ((df_merged["data_fim"].isna()) | (df_merged["data_checkin"] <= df_merged["data_fim"]))
].copy()

In [ ]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 535299 entries, 0 to 557999
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   nome_aluno     535299 non-null  object
 1   data_checkin   535299 non-null  object
 2   id_checkin     535299 non-null  int64
 3   data_checkout  535299 non-null  object
 4   idade_aluno    535299 non-null  int64
 5   data_inicio    535299 non-null  object
 6   data_fim       143435 non-null  object
dtypes: int64(2), object(5)
memory usage: 32.7+ MB

In [ ]:
df_merged["data_checkin"] = df_merged["data_checkin"].dt.strftime("%Y-%m-%d %H:%M:%S")
df_merged["data_checkout"] = df_merged["data_checkout"].dt.strftime("%Y-%m-%d %H:%M:%S")
df_merged["data_inicio"] = df_merged["data_inicio"].dt.strftime("%Y-%m-%d %H:%M:%S")
df_merged["data_fim"] = df_merged["data_fim"].dt.strftime("%Y-%m-%d %H:%M:%S")

In [ ]:
alunos_unicos = df_merged["nome_aluno"].unique()

In [ ]:
np.random.seed(42)
valores_aleatorios = np.random.uniform(low=69.90, high=229.90, size=len(alunos_unicos))

In [ ]:
df_planos = pd.DataFrame({"nome_aluno": alunos_unicos, "valor1": valores_aleatorios})

In [ ]:
df_planos["valor_plano"] = np.select(
    [df_planos["valor1"] <= 159.90, df_planos["valor1"] <= 229.89],
    [69.90, 159.90],
    default=229.90
)

In [ ]:
df_planos["nome_plano"] = np.select(
    [df_planos["valor_plano"] == 69.90, df_planos["valor_plano"] == 159.90],
    ["Beginner", "Focus"],
    default="Athlete"
)

In [ ]:
df_planos["tipo_plano"] = np.select(
    [df_planos["valor_plano"] == 69.90, df_planos["valor_plano"] == 159.90],
    ["Mensal", "Semestral"],
    default="Anual"
)

In [ ]:
df_merged = df_merged.merge(df_planos, on="nome_aluno", how="left")

In [ ]:
df_merged.columns

Index(['nome_aluno', 'data_checkin', 'id_checkin', 'data_checkout',
       'idade_aluno', 'data_inicio', 'data_fim', 'valor1', 'valor_plano',
       'nome_plano', 'tipo_plano'],
      dtype='object')

In [ ]:
df_merged["churn"] = df_merged["data_fim"].isna().astype(int)

In [ ]:
df_merged = df_merged[[
    'id_checkin',
    'nome_aluno',
    'idade_aluno',
    'data_checkin',
    'data_checkout',
    'data_inicio',
    'data_fim',
    'valor_plano',
    'nome_plano',
    'tipo_plano',
    'churn'
]]

In [ ]:
df_merged.sample(10)

,id_checkin,nome_aluno,idade_aluno,data_checkin,data_checkout,data_inicio,data_fim,valor_plano,nome_plano,tipo_plano,churn
398739,415524,Olivero Fourcade,17,2024-11-10 20:09:19,2024-11-10 21:07:19,2024-09-30 00:00:00,NaN,159.9,Focus,Semestral,1
72383,75351,Brook Gregs,31,2024-07-27 01:29:02,2024-07-27 02:23:02,2024-05-15 00:00:00,NaN,159.9,Focus,Semestral,1
201618,210631,Georgia Barck,55,2024-11-17 16:46:15,2024-11-17 17:39:15,2024-10-19 00:00:00,2025-10-27 00:00:00,159.9,Focus,Semestral,0
135160,140996,Devinne Kohnen,37,2025-04-03 18:10:30,2025-04-03 19:10:30,2025-04-03 00:00:00,NaN,69.9,Beginner,Mensal,1
109300,114144,Coral Eslinger,33,2025-03-16 13:08:02,2025-03-16 14:00:02,2024-07-31 00:00:00,2025-11-18 00:00:00,159.9,Focus,Semestral,0
324755,338544,Lonnie Bithell,39,2024-09-25 15:58:37,2024-09-25 16:56:37,2024-01-18 00:00:00,NaN,159.9,Focus,Semestral,1
109418,114262,Coralyn Triplow,55,2024-03-09 14:47:20,2024-03-09 15:28:20,2024-01-19 00:00:00,NaN,69.9,Beginner,Mensal,1
401405,418411,Orbadiah Chipp,42,2025-03-31 15:33:09,2025-03-31 16:31:09,2024-10-28 00:00:00,NaN,159.9,Focus,Semestral,1
409540,426866,Paulie Tugman,44,2025-03-27 17:17:11,2025-03-27 18:05:11,2025-01-15 00:00:00,NaN,159.9,Focus,Semestral,1
534550,557252,Zenia Pittford,36,2025-03-11 10:47:28,2025-03-11 11:28:28,2025-02-06 00:00:00,NaN,69.9,Beginner,Mensal,1

In [ ]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535299 entries, 0 to 535298
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id_checkin     535299 non-null  int64
 1   nome_aluno     535299 non-null  object
 2   idade_aluno    535299 non-null  int64
 3   data_checkin   535299 non-null  object
 4   data_checkout  535299 non-null  object
 5   data_inicio    535299 non-null  object
 6   data_fim       143435 non-null  object
 7   valor_plano    535299 non-null  float64
 8   nome_plano     535299 non-null  object
 9   tipo_plano     535299 non-null  object
 10  churn          535299 non-null  int64
dtypes: float64(1), int64(3), object(7)
memory usage: 44.9+ MB

In [ ]:
df_merged.to_csv('main_data.csv', index=False)