In [55]:
import pandas as pd

In [ ]:
# os dados são falsos/fictícios e foram gerados com https://www.mockaroo.com/

m1 = pd.read_csv("../../data/MOCK_DATA.csv")
m2 = pd.read_csv("../../data/MOCK_DATA(1).csv")
m3 = pd.read_csv("../../data/MOCK_DATA(2).csv")
m4 = pd.read_csv("../../data/MOCK_DATA(3).csv")
m5 = pd.read_csv("../../data/MOCK_DATA(4).csv")
m6 = pd.read_csv("../../data/MOCK_DATA(5).csv")
m7 = pd.read_csv("../../data/MOCK_DATA(6).csv")
m8 = pd.read_csv("../../data/MOCK_DATA(7).csv")
m9 = pd.read_csv("../../data/MOCK_DATA(8).csv")
m10 = pd.read_csv("../../data/MOCK_DATA(9).csv")

In [57]:
dfs = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10]
df = pd.concat(dfs, ignore_index=True)

In [58]:
df

             nome_aluno data_checkin data_inicio
0        Gerrie Pernell   2024-10-14  2025-01-08
1        Marielle Celli   2024-11-28  2024-12-29
2       Malvina Volante   2024-07-14  2024-10-22
3         Michal Spoure   2024-10-23  2024-12-19
4      Clotilda Donaghy   2024-07-24  2024-10-24
...                 ...          ...         ...
9995         Tedi Dyble   2024-06-10  2024-12-16
9996        Nedi Gasker   2024-12-30  2024-11-09
9997    Dickie Kennelly   2024-05-05  2024-12-07
9998      Devland Tames   2024-08-12  2024-11-19
9999  Valencia Stilwell   2024-09-18  2024-10-16

[10000 rows x 3 columns]

In [59]:
len(df["nome_aluno"].unique())

10000

In [60]:
import numpy as np

In [61]:
random_ages = np.random.randint(low=16, high=65, size=10_000)

In [62]:
df["idade_aluno"] = random_ages

In [63]:
df

             nome_aluno data_checkin data_inicio  idade_aluno
0        Gerrie Pernell   2024-10-14  2025-01-08           28
1        Marielle Celli   2024-11-28  2024-12-29           37
2       Malvina Volante   2024-07-14  2024-10-22           45
3         Michal Spoure   2024-10-23  2024-12-19           56
4      Clotilda Donaghy   2024-07-24  2024-10-24           28
...                 ...          ...         ...          ...
9995         Tedi Dyble   2024-06-10  2024-12-16           51
9996        Nedi Gasker   2024-12-30  2024-11-09           16
9997    Dickie Kennelly   2024-05-05  2024-12-07           38
9998      Devland Tames   2024-08-12  2024-11-19           31
9999  Valencia Stilwell   2024-09-18  2024-10-16           53

[10000 rows x 4 columns]

In [64]:
df["data_checkin"]

0       2024-10-14
1       2024-11-28
2       2024-07-14
3       2024-10-23
4       2024-07-24
           ...
9995    2024-06-10
9996    2024-12-30
9997    2024-05-05
9998    2024-08-12
9999    2024-09-18
Name: data_checkin, Length: 10000, dtype: object

In [65]:
!pip install pytz

Requirement already satisfied: pytz in /usr/local/lib/python3.11/dist-packages (2025.2)

In [66]:
import datetime
import random
import pytz

tz = pytz.timezone('America/Sao_Paulo')

def gerar_data_horario_aleatorio(data):
    hora = random.randint(6, 22)
    minuto = random.randint(0, 59)
    segundo = random.randint(0, 59)

    dt = datetime.datetime.strptime(data, "%Y-%m-%d")
    dt = dt.replace(hour=hora, minute=minuto, second=segundo)

    dt = tz.localize(dt)

    return dt.strftime("%Y-%m-%d %H:%M:%S%z")

df['data_checkin'] = df['data_checkin'].apply(gerar_data_horario_aleatorio)

In [67]:
df['data_checkin'] = pd.to_datetime(df['data_checkin'], format="%Y-%m-%d %H:%M:%S%z")

def gerar_data_checkout(data_checkin):
    minutos_extra = random.randint(40, 60)
    return data_checkin + datetime.timedelta(minutes=minutos_extra)

df['data_checkout'] = df['data_checkin'].apply(gerar_data_checkout)

df['data_checkout'] = df['data_checkout'].dt.strftime("%Y-%m-%d %H:%M:%S%z")

In [68]:
df

,nome_aluno,data_checkin,data_inicio,idade_aluno,data_checkout
0,Gerrie Pernell,2024-10-14 18:48:10-03:00,2025-01-08,28,2024-10-14 19:28:10-0300
1,Marielle Celli,2024-11-28 09:22:49-03:00,2024-12-29,37,2024-11-28 10:03:49-0300
2,Malvina Volante,2024-07-14 08:31:57-03:00,2024-10-22,45,2024-07-14 09:29:57-0300
3,Michal Spoure,2024-10-23 11:15:45-03:00,2024-12-19,56,2024-10-23 11:58:45-0300
4,Clotilda Donaghy,2024-07-24 19:26:34-03:00,2024-10-24,28,2024-07-24 20:07:34-0300
...,...,...,...,...,...
9995,Tedi Dyble,2024-06-10 21:36:35-03:00,2024-12-16,51,2024-06-10 22:16:35-0300
9996,Nedi Gasker,2024-12-30 15:37:16-03:00,2024-11-09,16,2024-12-30 16:32:16-0300
9997,Dickie Kennelly,2024-05-05 08:02:38-03:00,2024-12-07,38,2024-05-05 08:55:38-0300
9998,Devland Tames,2024-08-12 11:53:18-03:00,2024-11-19,31,2024-08-12 12:48:18-0300
9999,Valencia Stilwell,2024-09-18 10:46:36-03:00,2024-10-16,53,2024-09-18 11:44:36-0300

In [69]:
df = df[["nome_aluno", "idade_aluno", "data_checkin", "data_checkout", "data_inicio"]]

In [70]:
df["data_inicio"]

0       2025-01-08
1       2024-12-29
2       2024-10-22
3       2024-12-19
4       2024-10-24
           ...
9995    2024-12-16
9996    2024-11-09
9997    2024-12-07
9998    2024-11-19
9999    2024-10-16
Name: data_inicio, Length: 10000, dtype: object

In [71]:
df['data_inicio'] = pd.to_datetime(df['data_inicio'], format="%Y-%m-%d")

def gerar_data_fim(data_inicio):
    dias_extra = random.randint(30, 365)
    return data_inicio + datetime.timedelta(days=dias_extra)

df['data_fim'] = df['data_inicio'].apply(gerar_data_fim)

df['data_fim'] = df['data_fim'].dt.strftime("%Y-%m-%d")

In [72]:
df

,nome_aluno,idade_aluno,data_checkin,data_checkout,data_inicio,data_fim
0,Gerrie Pernell,28,2024-10-14 18:48:10-03:00,2024-10-14 19:28:10-0300,2025-01-08,2025-09-26
1,Marielle Celli,37,2024-11-28 09:22:49-03:00,2024-11-28 10:03:49-0300,2024-12-29,2025-08-05
2,Malvina Volante,45,2024-07-14 08:31:57-03:00,2024-07-14 09:29:57-0300,2024-10-22,2025-01-19
3,Michal Spoure,56,2024-10-23 11:15:45-03:00,2024-10-23 11:58:45-0300,2024-12-19,2025-05-08
4,Clotilda Donaghy,28,2024-07-24 19:26:34-03:00,2024-07-24 20:07:34-0300,2024-10-24,2025-01-05
...,...,...,...,...,...,...
9995,Tedi Dyble,51,2024-06-10 21:36:35-03:00,2024-06-10 22:16:35-0300,2024-12-16,2025-05-06
9996,Nedi Gasker,16,2024-12-30 15:37:16-03:00,2024-12-30 16:32:16-0300,2024-11-09,2025-09-02
9997,Dickie Kennelly,38,2024-05-05 08:02:38-03:00,2024-05-05 08:55:38-0300,2024-12-07,2025-11-23
9998,Devland Tames,31,2024-08-12 11:53:18-03:00,2024-08-12 12:48:18-0300,2024-11-19,2025-02-02
9999,Valencia Stilwell,53,2024-09-18 10:46:36-03:00,2024-09-18 11:44:36-0300,2024-10-16,2025-01-28

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nome_aluno     10000 non-null  object
 1   idade_aluno    10000 non-null  int64
 2   data_checkin   10000 non-null  datetime64[ns, UTC-03:00]
 3   data_checkout  10000 non-null  object
 4   data_inicio    10000 non-null  datetime64[ns]
 5   data_fim       10000 non-null  object
dtypes: datetime64[ns, UTC-03:00](1), datetime64[ns](1), int64(1), object(3)
memory usage: 468.9+ KB

In [78]:
df["data_inicio"] = pd.to_datetime(df['data_inicio'], format="%Y-%m-%d")

In [80]:
df["data_fim"] = pd.to_datetime(df['data_fim'], format="%Y-%m-%d")

In [83]:
df["data_checkout"] = pd.to_datetime(df['data_checkout'], format="%Y-%m-%d %H:%M:%S%z")

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nome_aluno     10000 non-null  object
 1   idade_aluno    10000 non-null  int64
 2   data_checkin   10000 non-null  datetime64[ns, UTC-03:00]
 3   data_checkout  10000 non-null  datetime64[ns, UTC-03:00]
 4   data_inicio    10000 non-null  datetime64[ns]
 5   data_fim       10000 non-null  datetime64[ns]
 6   churn          10000 non-null  int64
dtypes: datetime64[ns, UTC-03:00](2), datetime64[ns](2), int64(2), object(1)
memory usage: 547.0+ KB

In [91]:
df["data_fim"][3182]

Timestamp('2025-04-02 00:00:00')

In [98]:
data_limite = df.loc[3182, "data_fim"]

df["churn"] = (df["data_fim"] <= data_limite).astype(int)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nome_aluno     10000 non-null  object
 1   idade_aluno    10000 non-null  int64
 2   data_checkin   10000 non-null  datetime64[ns, UTC-03:00]
 3   data_checkout  10000 non-null  datetime64[ns, UTC-03:00]
 4   data_inicio    10000 non-null  datetime64[ns]
 5   data_fim       10000 non-null  datetime64[ns]
 6   churn          10000 non-null  int64
dtypes: datetime64[ns, UTC-03:00](2), datetime64[ns](2), int64(2), object(1)
memory usage: 547.0+ KB

In [102]:
df["churn"].value_counts(normalize=True)

churn
0    0.7172
1    0.2828
Name: proportion, dtype: float64

In [103]:
df

,nome_aluno,idade_aluno,data_checkin,data_checkout,data_inicio,data_fim,churn
0,Gerrie Pernell,28,2024-10-14 18:48:10-03:00,2024-10-14 19:28:10-03:00,2025-01-08,2025-09-26,0
1,Marielle Celli,37,2024-11-28 09:22:49-03:00,2024-11-28 10:03:49-03:00,2024-12-29,2025-08-05,0
2,Malvina Volante,45,2024-07-14 08:31:57-03:00,2024-07-14 09:29:57-03:00,2024-10-22,2025-01-19,1
3,Michal Spoure,56,2024-10-23 11:15:45-03:00,2024-10-23 11:58:45-03:00,2024-12-19,2025-05-08,0
4,Clotilda Donaghy,28,2024-07-24 19:26:34-03:00,2024-07-24 20:07:34-03:00,2024-10-24,2025-01-05,1
...,...,...,...,...,...,...,...
9995,Tedi Dyble,51,2024-06-10 21:36:35-03:00,2024-06-10 22:16:35-03:00,2024-12-16,2025-05-06,0
9996,Nedi Gasker,16,2024-12-30 15:37:16-03:00,2024-12-30 16:32:16-03:00,2024-11-09,2025-09-02,0
9997,Dickie Kennelly,38,2024-05-05 08:02:38-03:00,2024-05-05 08:55:38-03:00,2024-12-07,2025-11-23,0
9998,Devland Tames,31,2024-08-12 11:53:18-03:00,2024-08-12 12:48:18-03:00,2024-11-19,2025-02-02,1
9999,Valencia Stilwell,53,2024-09-18 10:46:36-03:00,2024-09-18 11:44:36-03:00,2024-10-16,2025-01-28,1

In [111]:
np.random.seed(42)
df["valor1"] = np.random.uniform(low=69.90, high=229.90, size=10_000)

df["valor_plano"] = np.where(
    df["valor1"] <= 159.90, 69.90,
    np.where(df["valor1"] <= 229.89, 159.90, 229.90)
)

In [113]:
df.columns

Index(['nome_aluno', 'idade_aluno', 'data_checkin', 'data_checkout',
       'data_inicio', 'data_fim', 'churn', 'valor1', 'valor_plano'],
      dtype='object')

In [115]:
df = df[['nome_aluno', 'idade_aluno', 'data_checkin', 'data_checkout', 'data_inicio', 'data_fim', 'churn', 'valor_plano']]

In [123]:
df["nome_plano"] = np.where(
    df["valor_plano"] == 69.90, "Beginner",
    np.where(df["valor_plano"] == 159.90, "Focus", "Athlete")
)
df["nome_plano"]

0       Beginner
1          Focus
2          Focus
3          Focus
4       Beginner
          ...
9995       Focus
9996       Focus
9997       Focus
9998    Beginner
9999    Beginner
Name: nome_plano, Length: 10000, dtype: object

In [124]:
df["tipo_plano"] = np.where(
    df["valor_plano"] == 69.90, "Mensal",
    np.where(df["valor_plano"] == 159.90, "Semestral", "Anual")
)

df["tipo_plano"]

0          Mensal
1       Semestral
2       Semestral
3       Semestral
4          Mensal
          ...
9995    Semestral
9996    Semestral
9997    Semestral
9998       Mensal
9999       Mensal
Name: tipo_plano, Length: 10000, dtype: object

In [125]:
df

,nome_aluno,idade_aluno,data_checkin,data_checkout,data_inicio,data_fim,churn,valor_plano,nome_plano,tipo_plano
0,Gerrie Pernell,28,2024-10-14 18:48:10-03:00,2024-10-14 19:28:10-03:00,2025-01-08,2025-09-26,0,69.9,Beginner,Mensal
1,Marielle Celli,37,2024-11-28 09:22:49-03:00,2024-11-28 10:03:49-03:00,2024-12-29,2025-08-05,0,159.9,Focus,Semestral
2,Malvina Volante,45,2024-07-14 08:31:57-03:00,2024-07-14 09:29:57-03:00,2024-10-22,2025-01-19,1,159.9,Focus,Semestral
3,Michal Spoure,56,2024-10-23 11:15:45-03:00,2024-10-23 11:58:45-03:00,2024-12-19,2025-05-08,0,159.9,Focus,Semestral
4,Clotilda Donaghy,28,2024-07-24 19:26:34-03:00,2024-07-24 20:07:34-03:00,2024-10-24,2025-01-05,1,69.9,Beginner,Mensal
...,...,...,...,...,...,...,...,...,...,...
9995,Tedi Dyble,51,2024-06-10 21:36:35-03:00,2024-06-10 22:16:35-03:00,2024-12-16,2025-05-06,0,159.9,Focus,Semestral
9996,Nedi Gasker,16,2024-12-30 15:37:16-03:00,2024-12-30 16:32:16-03:00,2024-11-09,2025-09-02,0,159.9,Focus,Semestral
9997,Dickie Kennelly,38,2024-05-05 08:02:38-03:00,2024-05-05 08:55:38-03:00,2024-12-07,2025-11-23,0,159.9,Focus,Semestral
9998,Devland Tames,31,2024-08-12 11:53:18-03:00,2024-08-12 12:48:18-03:00,2024-11-19,2025-02-02,1,69.9,Beginner,Mensal
9999,Valencia Stilwell,53,2024-09-18 10:46:36-03:00,2024-09-18 11:44:36-03:00,2024-10-16,2025-01-28,1,69.9,Beginner,Mensal

In [126]:
df.columns

Index(['nome_aluno', 'idade_aluno', 'data_checkin', 'data_checkout',
       'data_inicio', 'data_fim', 'churn', 'valor_plano', 'nome_plano',
       'tipo_plano'],
      dtype='object')

In [130]:
df = df[['nome_aluno', 'idade_aluno', 'data_checkin', 'data_checkout', 'data_inicio', 'data_fim', 'valor_plano', 'nome_plano', 'tipo_plano', 'churn']]

In [ ]:
df.to_csv('../../data/data.csv', index=False)